name: Gitops

on:
  push:
    tags:
      - 'v*'

jobs:
  gitops:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get Version
        run: echo "VERSION=$(git describe --tags --abbrev=0 | cut -c 2-)" >> $GITHUB_ENV

      - name: Switch branch to gitops
        run: git checkout gitops

      - name: Get .helm
        run: git checkout v${VERSION} -- .helm

      - name: Update version
        run: sed -i "s/_version_/$VERSION/" .helm/values.yaml

      - run: git add .helm

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          commit_message: Version updated ${{ env.VERSION }}
          commit_prefix: "[AUTO]"
